[[themes]]
name = "main"
[themes.palette]
foreground = "#c9c9c9"
black = "#FFFFFF"
red = "#ff5555"
green = "#d6d4d4"
yellow = "#d6d4d4"
blue = "#d6d4d4"
magenta = "#d6d4d4"
cyan = "#c9c9c9"
white = "#bbbbbb"
bright_black = "#555555"
bright_red = "#ff5555"
bright_green = "#d6d4d4"
bright_yellow = "#f1fa8c"
bright_blue = "#ff0000"
bright_magenta = "#ff79c6"
bright_cyan = "#ff0000"
bright_white = "#ffffff"
